AllCops:
  NewCops: enable

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Enabled: false
